name: Create a comment on Issues
on:
  issues:
    types: [opened]
  workflow_dispatch:
    

jobs:
  comment-with-action:
   runs-on: ubuntu-latest
   steps:
      - name: "dump github context"
        run: echo "Push by ${{ github.actor }}"
        shell: bash

  event-payload:
    runs-on: ubuntu-latest
    steps:
      - name: dump github event-payload
        run: echo '${{ toJSON (github.event) }}' | jq
        shell: bash

      - name: Create comment
        uses: peter-evans/create-or-update-comment@v4
        with:
          issue-number: ${{ github.event.issue.number }}
          body: |
            This is a multi-line test comment
            - With GitHub **Markdown** :sparkles:
            - Created by [create-or-update-comment][1]

            [1]: https://github.com/peter-evans/create-or-update-comment
          reactions: '+1'  


  # comment-issue:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout code
  #       uses: actions/checkout@v2

  #     - name: Comment with API
  #       env:
  #         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  #       run: |
  #         gh api repos/${{ github.repository }}/issues/${{ github.event.issue.number }}/comments \ --field body="Me too"
  
  
  comment-issue:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Comment with API
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh api repos/${{ github.repository }}/issues/${{ github.event.issue.number }}/comments \
            -X POST \
            -f body="Testing for the Comment"

  List-Issues:
      runs-on: ubuntu-latest
      steps:
        - name: List the Issues with API
          run: |
             gh api repos/${{ github.repository }}/issues/comments \
             -X GET
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  # Update-Issues:
  #     runs-on: ubuntu-latest
  #     steps:
  #       - name: Update the Issues with API
  #         run: |
  #            gh api repos/${{ github.repository }}/issues/comments/${{ github.event.comment.id }} \
  #            -X PATCH
  #            -f body="Me Too"
  #         env:
  #           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  

  List-comments:
      runs-on: ubuntu-latest
      steps:
        - name: List comments
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          run: echo " Comment Id ${{ github.event.issues.comment.id }} "
          shell: bash
      

     
    
        

                    
      


